<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\ProductFaq;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $dermatology = Category::where('slug', 'dermatology-skin-care')->first();
        $gastro = Category::where('slug', 'gastroenterology-gut-health')->first();
        $pediatrics = Category::where('slug', 'pediatrics-child-healthcare')->first();
        $ortho = Category::where('slug', 'orthopedics-bone-health')->first();
        $vitality = Category::where('slug', 'general-vitality-tonics')->first();

        $products = [
            [
                'category_id' => $dermatology?->id,
                'name' => 'Scabicod Soap (Permethrin 1%)',
                'slug' => 'scabicod-soap-permethrin-1-percent',
                'generic_name' => 'Permethrin',
                'brand_name' => 'Scabicod Soap',
                'strength' => '1% w/w',
                'dosage_form' => 'Medicated Soap Bar',
                'pack_size' => '75 gm Bar',
                'manufacturer' => 'Green Darma Pharmaceuticals',
                'active_ingredients' => 'Permethrin BP 1% w/w',
                'market_price_range' => 'BDT 220.00 to BDT 250.00 (Generic Reference)',
                'short_description' => 'Scabicod Soap containing Permethrin 1% is a specialized medicated soap formulated to treat scabies and lice infestations, providing rapid relief from skin itching and irritation.',
                'full_description' => 'Scabicod Soap (Permethrin 1%) by Green Darma Pharmaceuticals offers an effective, easy-to-use topical solution for managing and eradicating skin parasitic infestations such as scabies and lice. Formulated with 1% Permethrin, a dermatologist-recommended ectoparasiticide, Scabicod Soap targets the nerve cell membranes of scabies mites and lice, causing paralysis and rapid elimination.',
                'pharmacology' => 'Permethrin is a synthetic pyrethroid active against a broad range of pests including lice, ticks, fleas, mites, and other arthropods. It acts on the nerve cell membrane of insects by disrupting the sodium channel current that regulates the polarization of the membrane. Delayed repolarization and paralysis of the nervous system of pests lead to their death.',
                'indications' => 'Indicated for the treatment and prevention of Scabies (Sarcoptes scabiei infestation), Pediculosis capitis (head lice), Pediculosis pubis (crab lice), and associated superficial skin parasitic infestations.',
                'dosage' => 'Lather the soap on wet skin covering the affected areas thoroughly (or from neck to feet for scabies). Leave the lather on skin for 5 to 10 minutes before rinsing thoroughly with clean water. Repeat usage as advised by a physician, typically once daily during active treatment.',
                'side_effects' => 'Transient burning, stinging, erythema, numbness, rash, or localized skin irritation.',
                'contraindications' => 'Hypersensitivity to Permethrin, synthetic pyrethroids, pyrethrins, or any ingredient in the soap formulation.',
                'precautions' => 'For external topical use only. Avoid contact with eyes, nose, mouth, and mucous membranes. In case of accidental contact, rinse thoroughly with water.',
                'pregnancy_lactation' => 'Pregnancy Category B. Permethrin is poorly absorbed through the skin. It should be used during pregnancy only if clearly needed. Exercise caution in lactating mothers.',
                'drug_interactions' => 'No significant drug interactions documented for topical Permethrin soap. Concurrent application of other topical medications or harsh skin cleansers should be avoided.',
                'storage' => 'Store below 30°C in a dry place protected from direct sunlight and heat. Keep out of reach of children.',
                'seo_title' => 'Scabicod Soap (Permethrin 1%) - Anti-Scabies Medicated Soap Bar | Green Darma',
                'meta_description' => 'Buy Scabicod Soap (Permethrin 1%) by Green Darma Pharmaceuticals. Effective medicated soap for treating scabies, skin mites, and lice in Bangladesh.',
                'meta_keywords' => 'Scabicod Soap, Permethrin 1% soap, anti scabies soap Bangladesh, scabies treatment soap, Green Darma Permethrin soap',
                'image_alt' => 'Scabicod Soap Permethrin 1 percent Green Darma Pharmaceuticals',
                'status' => 'published',
                'is_featured' => true,
                'faqs' => [
                    ['question' => 'What is Scabicod Soap used for?', 'answer' => 'Scabicod Soap is used to treat and prevent scabies (mite infestation) and lice infestations on the skin and scalp.'],
                    ['question' => 'How often should I use Scabicod Soap for scabies?', 'answer' => 'It is typically used during bathing once daily or as directed by a dermatologist. Leave lather on the skin for 5-10 minutes before rinsing.'],
                    ['question' => 'Can all family members use Scabicod Soap?', 'answer' => 'Yes, when scabies is diagnosed, treating all household members simultaneously helps prevent re-infestation.'],
                    ['question' => 'Is Scabicod Soap safe for sensitive skin?', 'answer' => 'Permethrin is generally well-tolerated, but mild temporary redness or stinging may occur. Consult a physician if severe irritation develops.'],
                    ['question' => 'What should I do if Scabicod Soap gets into my eyes?', 'answer' => 'Rinse immediately and thoroughly with clean, running water.'],
                ],
            ],
            [
                'category_id' => $dermatology?->id,
                'name' => 'Tinea Soap (Luliconazole 1%)',
                'slug' => 'tinea-soap-luliconazole-1-percent',
                'generic_name' => 'Luliconazole',
                'brand_name' => 'Tinea Soap',
                'strength' => '1% w/w',
                'dosage_form' => 'Medicated Soap Bar',
                'pack_size' => '75 gm Bar',
                'manufacturer' => 'Green Darma Pharmaceuticals',
                'active_ingredients' => 'Luliconazole INN 1% w/w',
                'market_price_range' => 'BDT 198.00 to BDT 530.00 (Generic Reference)',
                'short_description' => 'Tinea Soap formulated with Luliconazole 1% provides powerful broad-spectrum antifungal cleansing for ringworm, jock itch, and athlete\'s foot.',
                'full_description' => 'Tinea Soap (Luliconazole 1%) by Green Darma Pharmaceuticals is a specialized medicated antifungal bar designed to combat superficial fungal skin infections. Powered by 1% Luliconazole, one of the most potent azole antifungals available, Tinea Soap targets the fungal cell wall to eliminate dermatophytes responsible for ringworm (Tinea corporis), jock itch (Tinea cruris), and athlete\'s foot (Tinea pedis).',
                'pharmacology' => 'Luliconazole is a broad-spectrum imidazole antifungal agent. It exerts fungicidal activity by selectively inhibiting the enzyme lanosterol 14-alpha-demethylase, which converts lanosterol to ergosterol. Disruption of ergosterol synthesis weakens the fungal cell membrane, leading to fungal cell death.',
                'indications' => 'Indicated for the topical treatment of fungal skin infections including Tinea pedis (athlete\'s foot), Tinea cruris (jock itch), Tinea corporis (ringworm), and Tinea versicolor.',
                'dosage' => 'Apply soap to wet skin in the affected areas and surrounding skin to form a rich lather. Allow the lather to sit for 3 to 5 minutes, then rinse thoroughly with water. Use once daily for 1 to 2 weeks or as directed by a healthcare professional.',
                'side_effects' => 'Mild application site reactions including pruritus, localized irritation, erythema, or contact dermatitis.',
                'contraindications' => 'Hypersensitivity to Luliconazole or any other azole antifungal agents.',
                'precautions' => 'For external topical use only. Avoid contact with eyes, mouth, and internal mucous membranes. If hypersensitivity or severe allergic reaction occurs, discontinue use immediately.',
                'pregnancy_lactation' => 'Pregnancy Category C. Limited clinical data in pregnant women. Use during pregnancy only if potential benefits outweigh fetus risks. Caution during lactation.',
                'drug_interactions' => 'No major systemic drug interactions reported with topical Luliconazole. Avoid simultaneous application of other topical antifungal formulations on the same site.',
                'storage' => 'Store below 30°C in a dry place. Protect from direct heat and light. Keep away from children.',
                'seo_title' => 'Tinea Soap (Luliconazole 1%) - Antifungal Medicated Soap | Green Darma',
                'meta_description' => 'Treat ringworm and fungal infections with Tinea Soap (Luliconazole 1%) by Green Darma Pharmaceuticals. Powerful broad-spectrum antifungal soap bar in Bangladesh.',
                'meta_keywords' => 'Tinea Soap, Luliconazole 1% soap, antifungal soap Bangladesh, ringworm soap, Green Darma Luliconazole soap',
                'image_alt' => 'Tinea Soap Luliconazole 1 percent Green Darma Pharmaceuticals',
                'status' => 'published',
                'is_featured' => true,
                'faqs' => [
                    ['question' => 'What is Tinea Soap used for?', 'answer' => 'Tinea Soap is used to treat fungal skin infections like ringworm, jock itch, athlete\'s foot, and tinea versicolor.'],
                    ['question' => 'How long should I leave Tinea Soap lather on my skin?', 'answer' => 'Leave the lather on affected areas for 3-5 minutes before rinsing with water.'],
                    ['question' => 'How long does it take for Tinea Soap to show results?', 'answer' => 'Symptoms like itching often improve within a few days, but treatment should continue for 1-2 weeks for complete eradication.'],
                    ['question' => 'Can I use Tinea Soap on my face?', 'answer' => 'Yes, if prescribed for facial fungal infection, but strictly avoid contact with eyes, nostrils, and mouth.'],
                    ['question' => 'Is Tinea Soap suitable for daily use?', 'answer' => 'Yes, it can be used once daily during active infection treatment or as advised by your physician.'],
                ],
            ],
            [
                'category_id' => $dermatology?->id,
                'name' => 'Scabvar Lotion (Permethrin 5% + Crotamiton 10%)',
                'slug' => 'scabvar-lotion-permethrin-5-crotamiton-10',
                'generic_name' => 'Permethrin + Crotamiton',
                'brand_name' => 'Scabvar Lotion',
                'strength' => '5% w/v + 10% w/v',
                'dosage_form' => 'Topical Lotion',
                'pack_size' => '60 ml Bottle',
                'manufacturer' => 'Green Darma Pharmaceuticals',
                'active_ingredients' => 'Permethrin BP 5% w/v + Crotamiton USP 10% w/v',
                'market_price_range' => 'BDT 160.00 to BDT 255.00 (Generic Reference)',
                'short_description' => 'Scabvar Lotion combines Permethrin 5% and Crotamiton 10% for fast-acting scabies eradication and immediate anti-itch relief.',
                'full_description' => 'Scabvar Lotion (Permethrin 5% + Crotamiton 10%) by Green Darma Pharmaceuticals represents a dual-action therapeutic formulation for scabies management. While 5% Permethrin eradicates scabies mites and their eggs at all life stages, 10% Crotamiton acts rapidly to soothe agonizing skin itching and pruritus.',
                'pharmacology' => 'Scabvar Lotion combines Permethrin (5%) and Crotamiton (10%). Permethrin is a neurotoxic scabicide that paralyzes and kills Sarcoptes scabiei mites and their eggs. Crotamiton provides dual action: it acts as a scabicide and possesses potent anti-pruritic properties.',
                'indications' => 'Indicated for the comprehensive treatment of Scabies (Sarcoptes scabiei infestation), severe skin itching (pruritus), pediculosis, and associated cutaneous parasitic conditions.',
                'dosage' => 'Thoroughly massage lotion into clean, cool, dry skin from the neck down to the soles of feet. Pay special attention to skin folds, between fingers/toes, wrists, armpits, and groin. Leave lotion on for 8 to 14 hours (usually overnight) before washing off thoroughly.',
                'side_effects' => 'Temporary skin burning, stinging, redness, mild irritation, or localized contact allergic reaction.',
                'contraindications' => 'Hypersensitivity to Permethrin, Crotamiton, pyrethroids, or any component of the lotion. Acute exudative or oozing dermatitis.',
                'precautions' => 'For external topical use only. Do not apply on broken, inflamed, or infected skin or mucous membranes. Avoid contact with eyes.',
                'pregnancy_lactation' => 'Pregnancy Category B. Use during pregnancy only if clearly indicated by a doctor. Excretion in breast milk is minimal, but nursing should be temporarily suspended during application.',
                'drug_interactions' => 'Avoid concurrent use with other topical anti-pruritics, corticosteroids, or skin preparations that may alter skin permeability.',
                'storage' => 'Store below 30°C in a dry place. Protect from heat and direct sunlight. Keep container tightly closed.',
                'seo_title' => 'Scabvar Lotion (Permethrin 5% + Crotamiton 10%) - Scabies Treatment | Green Darma',
                'meta_description' => 'Scabvar Lotion (Permethrin 5% + Crotamiton 10%) by Green Darma. Dual action scabies lotion for fast mite elimination and itching relief in Bangladesh.',
                'meta_keywords' => 'Scabvar Lotion, Permethrin Crotamiton lotion, scabies lotion Bangladesh, anti itch scabies treatment, Green Darma scabicide',
                'image_alt' => 'Scabvar Lotion Permethrin 5 percent Crotamiton 10 percent Green Darma Pharmaceuticals',
                'status' => 'published',
                'is_featured' => true,
                'faqs' => [
                    ['question' => 'How does Scabvar Lotion differ from regular Permethrin lotion?', 'answer' => 'Scabvar Lotion combines Permethrin 5% with Crotamiton 10%, offering dual benefit: mite destruction plus instant relief from severe itching.'],
                    ['question' => 'How long should Scabvar Lotion remain on the skin?', 'answer' => 'It should be left on the body for 8 to 14 hours (typically overnight) before washing off completely.'],
                    ['question' => 'Should family members also use Scabvar Lotion?', 'answer' => 'Yes, all household contacts and close partners should be treated at the same time to prevent cross-reinfestation.'],
                    ['question' => 'Is one application of Scabvar Lotion enough?', 'answer' => 'A single thorough application is usually curative. A second application after 7 days may be recommended if live mites persist.'],
                    ['question' => 'Can Scabvar Lotion be applied on the face?', 'answer' => 'In adults, avoid facial application unless directed by a dermatologist. For infants, avoid mouth and eye areas.'],
                ],
            ],
            [
                'category_id' => $dermatology?->id,
                'name' => 'Greenstar Shampoo (Ketoconazole 2% + ZPTO + Aloe Vera)',
                'slug' => 'greenstar-shampoo-ketoconazole-zpto-aloe-vera',
                'generic_name' => 'Ketoconazole + Zinc Pyrithione + Aloe Vera',
                'brand_name' => 'Greenstar Shampoo',
                'strength' => 'Ketoconazole 2% w/v + ZPTO 1% w/v + Aloe Vera 1% w/v',
                'dosage_form' => 'Medicated Antidandruff Shampoo',
                'pack_size' => '100 ml Bottle',
                'manufacturer' => 'Green Darma Pharmaceuticals',
                'active_ingredients' => 'Ketoconazole USP 2% w/v + Zinc Pyrithione (ZPTO) 1% w/v + Aloe Vera Extract 1% w/v',
                'market_price_range' => 'BDT 250.00 to BDT 690.00 (Generic Reference)',
                'short_description' => 'Greenstar Shampoo with Ketoconazole 2%, Zinc Pyrithione, and Aloe Vera delivers clinical relief from scalp dandruff, itching, and seborrheic dermatitis.',
                'full_description' => 'Greenstar Shampoo (Ketoconazole 2% + Zinc Pyrithione + Aloe Vera) by Green Darma Pharmaceuticals is a premium anti-dandruff hair care formulation. Designed to eliminate dandruff at its root cause, Greenstar combines the antifungal potency of Ketoconazole 2% with the scaling-control action of Zinc Pyrithione.',
                'pharmacology' => 'Ketoconazole is an imidazole antifungal that eradicates Malassezia (Pityrosporum) yeast, the principal causative fungal agent of scalp dandruff. Zinc Pyrithione exhibits potent cytostatic and antimicrobial action. Aloe Vera provides natural skin conditioning and soothing hydration.',
                'indications' => 'Indicated for the treatment and prevention of stubborn dandruff, Seborrheic Dermatitis of the scalp, Pityriasis Versicolor, and itchy, flaking scalp conditions.',
                'dosage' => 'Apply sufficient shampoo to wet hair and scalp to build a rich lather. Massage scalp gently with fingertips. Leave lather on scalp for 3 to 5 minutes before rinsing thoroughly with water. Use twice weekly for 2 to 4 weeks during active treatment.',
                'side_effects' => 'Occasional scalp irritation, dry hair, altered hair texture, or localized itching/burning sensation.',
                'contraindications' => 'Known hypersensitivity to Ketoconazole, Zinc Pyrithione, Aloe Vera, or any shampoo excipients.',
                'precautions' => 'For external hair and scalp use only. Avoid contact with eyes. If shampoo gets into eyes, flush immediately with clean water.',
                'pregnancy_lactation' => 'Minimal systemic absorption occurs following topical scalp application. Safe to use during pregnancy and lactation under medical guidance.',
                'drug_interactions' => 'Avoid simultaneous use with topical scalp corticosteroids without doctor supervision; taper steroid dosage gradually when initiating Ketoconazole shampoo.',
                'storage' => 'Store below 30°C in a dry place. Keep container tightly closed and protect from direct sunlight.',
                'seo_title' => 'Greenstar Shampoo (Ketoconazole 2% + ZPTO + Aloe Vera) | Green Darma',
                'meta_description' => 'Eliminate severe dandruff and scalp itching with Greenstar Shampoo by Green Darma Pharmaceuticals. Formulated with Ketoconazole 2%, ZPTO, and Aloe Vera.',
                'meta_keywords' => 'Greenstar Shampoo, Ketoconazole ZPTO shampoo, anti dandruff shampoo Bangladesh, Green Darma shampoo, seborrheic dermatitis shampoo',
                'image_alt' => 'Greenstar Shampoo Ketoconazole 2 percent Zinc Pyrithione Aloe Vera Green Darma Pharmaceuticals',
                'status' => 'published',
                'is_featured' => true,
                'faqs' => [
                    ['question' => 'What makes Greenstar Shampoo effective against severe dandruff?', 'answer' => 'It combines Ketoconazole 2% (kills dandruff yeast) and Zinc Pyrithione (controls scaling), enhanced with Aloe Vera for soothing hydration.'],
                    ['question' => 'How often should I use Greenstar Shampoo?', 'answer' => 'Use twice weekly for 2-4 weeks during active treatment. For maintenance, use once weekly or every two weeks.'],
                    ['question' => 'How long should I leave Greenstar Shampoo on my scalp?', 'answer' => 'Leave the lather on your scalp for 3 to 5 minutes before rinsing thoroughly.'],
                    ['question' => 'Can Greenstar Shampoo cause hair dryness?', 'answer' => 'Aloe Vera helps retain moisture, but if dryness occurs, use a hair conditioner on hair ends after rinsing.'],
                    ['question' => 'Is Greenstar Shampoo suitable for color-treated hair?', 'answer' => 'Yes, but perform a strand test if you have freshly dyed or bleached hair.'],
                ],
            ],
            [
                'category_id' => $gastro?->id,
                'name' => 'SASAT G-Biotic (Probiotic 3 Billion CFU)',
                'slug' => 'sasat-g-biotic-probiotic-3-billion-cfu',
                'generic_name' => 'Multi-Strain Probiotic Supplement',
                'brand_name' => 'SASAT G-Biotic',
                'strength' => '3 Billion CFU (Colony Forming Units)',
                'dosage_form' => 'Capsule / Sachet',
                'pack_size' => '30 Capsules / 10 Sachets',
                'manufacturer' => 'Green Darma Pharmaceuticals',
                'active_ingredients' => 'Lactobacillus acidophilus, Bifidobacterium longum, Bifidobacterium bifidum, Streptococcus thermophilus (Total Viable Count: 3 Billion CFU)',
                'market_price_range' => 'BDT 300.00 to BDT 600.00 (Generic Reference)',
                'short_description' => 'SASAT G-Biotic contains 3 Billion CFU of beneficial probiotic strains to restore gut microflora, soothe indigestion, and support digestive immunity.',
                'full_description' => 'SASAT G-Biotic (Probiotic 3 Billion CFU) by Green Darma Pharmaceuticals is a premium digestive healthcare formula engineered to restore and maintain optimum intestinal health. Supplying 3 Billion viable probiotic organisms per dose, SASAT G-Biotic repopulates the gut microbiome with beneficial bacteria.',
                'pharmacology' => 'SASAT G-Biotic delivers 3 Billion Live Colony Forming Units (CFU) of beneficial probiotic microorganisms. These live beneficial bacteria colonize the gastrointestinal tract, restoring intestinal microflora balance disturbed by antibiotics, infections, or poor diet.',
                'indications' => 'Indicated for Antibiotic-Associated Diarrhea (AAD), Irritable Bowel Syndrome (IBS), acute gastroenteritis, indigestion, bloating, gut dysbiosis, lactose intolerance, and boosting digestive immunity.',
                'dosage' => 'Adults: 1 to 2 capsules/sachets daily after meals with water. Children (if taking sachet): 1 sachet daily mixed with cool water, milk, or juice.',
                'side_effects' => 'Mild initial gastrointestinal gas, bloating, or abdominal discomfort during the first few days of therapy as microflora adjusts.',
                'contraindications' => 'Hypersensitivity to any probiotic strain or excipient. Severely immunocompromised patients (e.g., organ transplant recipients, severe neutropenia).',
                'precautions' => 'Do not mix probiotic powders with hot drinks or food (heat destroys live probiotic cultures). Take probiotic supplements at least 2 hours apart from oral antibiotics.',
                'pregnancy_lactation' => 'Probiotics are non-systemic and generally recognized as safe (GRAS) during pregnancy and lactation. Consult a doctor before starting supplementation.',
                'drug_interactions' => 'Antibacterial and antifungal drugs may reduce probiotic efficacy; space administration by at least 2 hours.',
                'storage' => 'Store below 25°C in a cool, dry place away from moisture and direct heat. Refrigeration recommended after opening.',
                'seo_title' => 'SASAT G-Biotic (Probiotic 3 Billion CFU) - Gut Health | Green Darma',
                'meta_description' => 'Restore gut microbiome with SASAT G-Biotic (Probiotic 3 Billion CFU) by Green Darma. Effective probiotic for digestion, IBS, and antibiotic diarrhea in Bangladesh.',
                'meta_keywords' => 'SASAT G-Biotic, Probiotic 3 Billion CFU, gut health supplement Bangladesh, probiotic capsule, Green Darma probiotic',
                'image_alt' => 'SASAT G-Biotic Probiotic 3 Billion CFU Green Darma Pharmaceuticals',
                'status' => 'published',
                'is_featured' => true,
                'faqs' => [
                    ['question' => 'What is SASAT G-Biotic used for?', 'answer' => 'SASAT G-Biotic is used to restore healthy gut bacteria, treat antibiotic-induced diarrhea, improve digestion, and relieve bloating or IBS symptoms.'],
                    ['question' => 'When should I take SASAT G-Biotic relative to antibiotics?', 'answer' => 'Take SASAT G-Biotic at least 2 hours before or after taking your antibiotic dose.'],
                    ['question' => 'Does SASAT G-Biotic require refrigeration?', 'answer' => 'Store in a cool, dry place below 25°C. Refrigeration helps maintain maximum live bacterial count over time.'],
                    ['question' => 'Is SASAT G-Biotic safe for daily long-term use?', 'answer' => 'Yes, probiotic supplements are safe for ongoing daily use to maintain gut balance.'],
                    ['question' => 'Can children take SASAT G-Biotic?', 'answer' => 'Yes, pediatric dosing (usually sachet form) can be administered under physician guidance.'],
                ],
            ],
            [
                'category_id' => $pediatrics?->id,
                'name' => 'Pradiatic Drop VD3 (Vitamin D3 + Multivitamin)',
                'slug' => 'pradiatic-drop-vd3-vitamin-d3-multivitamin',
                'generic_name' => 'Vitamin D3 + Multivitamin Pediatric Drops',
                'brand_name' => 'Pradiatic Drop VD3',
                'strength' => 'Vitamin D3 (Cholecalciferol 400 IU) + Vitamin A, C, B-Complex per ml',
                'dosage_form' => 'Pediatric Oral Drop',
                'pack_size' => '15 ml / 30 ml Dropper Bottle',
                'manufacturer' => 'Green Darma Pharmaceuticals',
                'active_ingredients' => 'Cholecalciferol (Vitamin D3) 400 IU + Vitamin A 1500 IU + Vitamin C 30 mg + Vitamin B1 0.5 mg + Vitamin B2 0.6 mg + Nicotinamide 5 mg per ml',
                'market_price_range' => 'BDT 120.00 to BDT 250.00 (Generic Reference)',
                'short_description' => 'Pradiatic Drop VD3 provides Vitamin D3 400 IU and essential multivitamin nutrition for infants, supporting healthy bone growth, immune strength, and rickets prevention.',
                'full_description' => 'Pradiatic Drop VD3 (Vitamin D3 + Multivitamin) by Green Darma Pharmaceuticals is a pediatric nutritional drops formulation tailored for infants and young children. Combining recommended daily Vitamin D3 (400 IU) with essential vitamins (A, C, and B-Complex), Pradiatic Drop VD3 ensures optimal skeletal development.',
                'pharmacology' => 'Pradiatic Drop VD3 provides essential vitamins required for infant growth and skeletal development. Vitamin D3 (Cholecalciferol) facilitates calcium and phosphate absorption in the intestine, promoting bone mineralization and preventing rickets.',
                'indications' => 'Indicated for infants and young children for prevention and treatment of Vitamin D3 deficiency, prevention of pediatric rickets, support of bone growth and dentition, and nutritional supplementation.',
                'dosage' => 'Infants (0-12 months): 1 ml daily or as prescribed by a pediatrician. Children (1-3 years): 1 ml to 2 ml daily. Can be administered directly into the mouth using the calibrated dropper or mixed with milk, fruit juice, or baby food.',
                'side_effects' => 'Generally well-tolerated at recommended doses. Excessive dosage may cause hypercalcemia, loss of appetite, nausea, vomiting, or restlessness.',
                'contraindications' => 'Hypercalcemia, hypervitaminosis D, or known hypersensitivity to any constituent.',
                'precautions' => 'Do not exceed recommended pediatric daily allowance. Monitor serum calcium in children receiving high-dose Vitamin D therapy concurrently.',
                'pregnancy_lactation' => 'Formulated specifically for pediatric/infant administration. (Maternal use of multivitamin drops is not applicable).',
                'drug_interactions' => 'Thiazide diuretics may increase hypercalcemia risk with high Vitamin D. Anticonvulsants (phenytoin, carbamazepine) accelerate Vitamin D clearance.',
                'storage' => 'Store below 25°C in a cool, dry place away from light. Keep container tightly closed after each use. Keep out of reach of children.',
                'seo_title' => 'Pradiatic Drop VD3 (Vitamin D3 + Multivitamin) Drops | Green Darma',
                'meta_description' => 'Pediatric Vitamin D3 multivitamin drops for infants by Green Darma Pharmaceuticals. Supports baby bone growth, rickets protection, and immunity in BD.',
                'meta_keywords' => 'Pradiatic Drop VD3, pediatric vitamin d3 drops Bangladesh, infant vitamin d drops, Green Darma VD3 drop, baby multivitamin drops',
                'image_alt' => 'Pradiatic Drop VD3 Vitamin D3 Multivitamin Green Darma Pharmaceuticals',
                'status' => 'published',
                'is_featured' => true,
                'faqs' => [
                    ['question' => 'Why do infants need Vitamin D3 drops like Pradiatic Drop VD3?', 'answer' => 'Breastfed infants and growing babies require Vitamin D3 to absorb calcium properly, build strong bones, and prevent nutritional rickets.'],
                    ['question' => 'How should Pradiatic Drop VD3 be given to a baby?', 'answer' => 'Use the provided dropper to administer 1 ml directly into the baby\'s mouth or mix it with breastmilk, formula, or cereal.'],
                    ['question' => 'Is Pradiatic Drop VD3 safe for newborns?', 'answer' => 'Yes, it is designed for pediatric use starting from infancy, as advised by a pediatrician.'],
                    ['question' => 'What happens if a dose is missed?', 'answer' => 'Give the missed dose when remembered on the same day, or skip and resume regular schedule. Do not double doses.'],
                    ['question' => 'Does Pradiatic Drop VD3 contain sugar or artificial colors?', 'answer' => 'It is formulated according to pediatric safety standards to ensure maximum gentle bioavailability.'],
                ],
            ],
            [
                'category_id' => $ortho?->id,
                'name' => 'X-Corel G Tablet (Coral Calcium 600mg + Vitamin D3 + Magnesium)',
                'slug' => 'x-corel-g-tablet-coral-calcium-vitamin-d3-magnesium',
                'generic_name' => 'Coral Calcium + Vitamin D3 + Magnesium',
                'brand_name' => 'X-Corel G Tablet',
                'strength' => 'Coral Calcium 600 mg + Vitamin D3 400 IU + Magnesium 365 mg',
                'dosage_form' => 'Film-Coated Tablet',
                'pack_size' => '30 Tablets Container / Blister',
                'manufacturer' => 'Green Darma Pharmaceuticals',
                'active_ingredients' => 'Coral Calcium (Organic Calcium Carbonate) 600 mg + Vitamin D3 (Cholecalciferol) 400 IU + Magnesium Oxide 365 mg',
                'market_price_range' => 'BDT 200.00 to BDT 450.00 (Generic Reference)',
                'short_description' => 'X-Corel G Tablet provides highly bioavailable Coral Calcium 600mg, Vitamin D3 400 IU, and Magnesium 365mg for optimal bone mineral density and osteoporosis protection.',
                'full_description' => 'X-Corel G Tablet (Coral Calcium 600mg + Vitamin D3 400 IU + Magnesium 365mg) by Green Darma Pharmaceuticals is an advanced organic bone health formulation. Formulated with natural Coral Calcium, X-Corel G offers superior absorption and gentler gastrointestinal tolerance than synthetic calcium salts.',
                'pharmacology' => 'X-Corel G combines natural Coral Calcium, Vitamin D3, and Magnesium. Coral Calcium, derived from natural marine coral deposits, has a porous chemical structure similar to human bone matrix, providing higher calcium bioavailability and absorption compared to elemental calcium carbonate.',
                'indications' => 'Indicated for the prevention and treatment of osteoporosis, osteomalacia, post-menopausal bone loss, calcium and magnesium deficiencies, bone fractures, and elevated calcium demand during pregnancy and lactation.',
                'dosage' => 'Adults: 1 tablet once or twice daily after meals with water, or as directed by a healthcare practitioner.',
                'side_effects' => 'Mild gastrointestinal upset, flatulence, constipation, or nausea in sensitive individuals.',
                'contraindications' => 'Hypercalcemia, hypercalciuria, severe renal impairment, nephrolithiasis (kidney stones), or hypermagnesemia.',
                'precautions' => 'Patients with mild to moderate renal impairment or a history of kidney stones should monitor serum and urinary calcium levels during long-term therapy.',
                'pregnancy_lactation' => 'Highly recommended during pregnancy and lactation due to increased maternal calcium and magnesium requirements. Consult an obstetrician for tailored dosing.',
                'drug_interactions' => 'Oral calcium may decrease absorption of tetracycline and fluoroquinolone antibiotics, bisphosphonates, and levothyroxine. Separate administration by 2 to 3 hours.',
                'storage' => 'Store below 30°C in a dry place protected from light and moisture. Keep container tightly closed.',
                'seo_title' => 'X-Corel G Tablet (Coral Calcium + Vitamin D3 + Magnesium) | Green Darma',
                'meta_description' => 'Boost bone strength with X-Corel G Tablet (Coral Calcium 600mg + Vitamin D3 + Magnesium 365mg) by Green Darma Pharmaceuticals. Osteoporosis protection in Bangladesh.',
                'meta_keywords' => 'X-Corel G Tablet, Coral Calcium Magnesium Vitamin D3, bone calcium supplement BD, Green Darma Coral Calcium, osteoporosis treatment',
                'image_alt' => 'X-Corel G Tablet Coral Calcium Vitamin D3 Magnesium Green Darma Pharmaceuticals',
                'status' => 'published',
                'is_featured' => true,
                'faqs' => [
                    ['question' => 'What are the key benefits of Coral Calcium in X-Corel G Tablet?', 'answer' => 'Coral Calcium has an organic structure similar to human bone, making it more easily absorbed and gentler on the stomach than synthetic calcium.'],
                    ['question' => 'Why is Magnesium included with Coral Calcium and Vitamin D3?', 'answer' => 'Magnesium is necessary to activate Vitamin D and ensure proper calcium fixation into bone tissue rather than soft tissue.'],
                    ['question' => 'Can pregnant women take X-Corel G Tablet?', 'answer' => 'Yes, calcium, magnesium, and vitamin D requirements increase during pregnancy and lactation, making X-Corel G an ideal supplement under doctor advice.'],
                    ['question' => 'When is the best time to take X-Corel G Tablet?', 'answer' => 'Take 1 tablet after meals with a full glass of water for maximum absorption.'],
                    ['question' => 'Does X-Corel G cause constipation?', 'answer' => 'Coral calcium is less likely to cause constipation than traditional calcium carbonate, though staying well-hydrated is always recommended.'],
                ],
            ],
            [
                'category_id' => $vitality?->id,
                'name' => 'Maxtarm Syrup (Multivitamin & Multimineral Tonic)',
                'slug' => 'maxtarm-syrup-multivitamin-multimineral',
                'generic_name' => 'Multivitamin & Multimineral Tonic Syrup',
                'brand_name' => 'Maxtarm Syrup',
                'strength' => 'Multivitamin + Iron + Zinc + Minerals per 5 ml',
                'dosage_form' => 'Oral Syrup',
                'pack_size' => '100 ml / 200 ml Bottle',
                'manufacturer' => 'Green Darma Pharmaceuticals',
                'active_ingredients' => 'Vitamin A, Vitamin B-Complex (B1, B2, B6, B12, Niacinamide), Vitamin C, Vitamin D3, Iron, Zinc, Lysine, Copper, Manganese per 5 ml',
                'market_price_range' => 'BDT 80.00 to BDT 220.00 (Generic Reference)',
                'short_description' => 'Maxtarm Syrup is a comprehensive multivitamin and multimineral vitality syrup formulated to boost appetite, combat weakness, and build immunity.',
                'full_description' => 'Maxtarm Syrup by Green Darma Pharmaceuticals is an all-in-one multivitamin, mineral, and energy-restoring health tonic. Formulated to address nutritional deficiencies, fatigue, and poor appetite, Maxtarm Syrup provides essential B-vitamins, Iron, Zinc, and Lysine.',
                'pharmacology' => 'Maxtarm Syrup combines essential vitamins, vital minerals, trace elements, and amino acids (L-Lysine). It fills daily dietary nutritional gaps, enhances cellular metabolism, stimulates appetite, and aids hemoglobin synthesis.',
                'indications' => 'Indicated for general weakness, loss of appetite, convalescence following illness, nutritional anemia, growing children, elderly health revitalization, and daily dietary micronutrient supplementation.',
                'dosage' => 'Adults: 2 teaspoonfuls (10 ml) twice daily after meals. Children (above 2 years): 1 teaspoonful (5 ml) once or twice daily after meals. Or as prescribed by a physician.',
                'side_effects' => 'Mild gastrointestinal upset, temporary dark stools (due to iron content), or transient nausea if taken on an empty stomach.',
                'contraindications' => 'Hypersensitivity to any vitamin or mineral component. Conditions with iron overload (e.g., hemochromatosis, hemosiderosis).',
                'precautions' => 'Take after meals to minimize gastric discomfort. Do not exceed recommended daily allowance. Keep out of reach of children to avoid accidental overdose.',
                'pregnancy_lactation' => 'Safe and beneficial during pregnancy and lactation under medical supervision to fulfill elevated micronutrient demands.',
                'drug_interactions' => 'Iron absorption may be reduced by antacids or oral tetracyclines. Separate administration times by at least 2 hours.',
                'storage' => 'Store below 30°C in a dry place protected from light and heat. Keep bottle tightly closed.',
                'seo_title' => 'Maxtarm Syrup (Multivitamin & Multimineral Tonic) | Green Darma',
                'meta_description' => 'Boost energy and immunity with Maxtarm Syrup by Green Darma Pharmaceuticals. Comprehensive multivitamin, iron, and zinc health tonic syrup in Bangladesh.',
                'meta_keywords' => 'Maxtarm Syrup, multivitamin syrup Bangladesh, health tonic syrup, Green Darma Maxtarm, appetite booster syrup',
                'image_alt' => 'Maxtarm Syrup Multivitamin Multimineral Health Tonic Green Darma Pharmaceuticals',
                'status' => 'published',
                'is_featured' => true,
                'faqs' => [
                    ['question' => 'What is Maxtarm Syrup used for?', 'answer' => 'Maxtarm Syrup is used to treat vitamin and mineral deficiencies, improve appetite, combat physical weakness, and boost overall immunity.'],
                    ['question' => 'Can Maxtarm Syrup improve appetite in children?', 'answer' => 'Yes, it contains L-Lysine and B-vitamins which naturally stimulate appetite and healthy weight gain in growing children.'],
                    ['question' => 'Is Maxtarm Syrup safe during pregnancy?', 'answer' => 'Yes, under physician guidance, multivitamin and mineral syrups help meet elevated nutritional requirements during pregnancy.'],
                    ['question' => 'Why do stools turn darker when taking Maxtarm Syrup?', 'answer' => 'This is a normal, harmless effect caused by the unabsorbed iron content in the syrup.'],
                    ['question' => 'Should Maxtarm Syrup be taken before or after food?', 'answer' => 'It is best taken after meals to enhance vitamin absorption and prevent stomach upset.'],
                ],
            ],
        ];

        foreach ($products as $pData) {
            $faqs = $pData['faqs'] ?? [];
            unset($pData['faqs']);

            $product = Product::updateOrCreate(
                ['slug' => $pData['slug']],
                $pData
            );

            $product->faqs()->delete();
            foreach ($faqs as $index => $faq) {
                ProductFaq::create([
                    'product_id' => $product->id,
                    'question' => $faq['question'],
                    'answer' => $faq['answer'],
                    'sort_order' => $index + 1,
                ]);
            }
        }
    }
}
